name = "f8assetcloud"
main = "src/index.js"
compatibility_date = "2026-03-31"
workers_dev = true

[assets]
directory = "./console_web/dist"
binding = "ASSETS"

[vars]
JWT_ISSUER = "feel8-asset-cloud"
BOOTSTRAP_ADMIN_USERNAME = "admin"
BOOTSTRAP_ADMIN_DISPLAY_NAME = "Administrator"
ACCESS_TOKEN_TTL_SECONDS = "3600"
REFRESH_TOKEN_TTL_SECONDS = "2592000"

[[d1_databases]]
binding = "DB"
database_name = "feel8-assets"
database_id = "0967331a-6656-4d74-a385-8baf458f4ecd"
preview_database_id = "c9b75abc-8ae7-48fa-9ac9-8f5d37f2336c"
migrations_dir = "migrations"
