from __future__ import annotations

LAUNCH_READY_FILE_ENV = "F8STUDIO_LAUNCH_READY_FILE"
LAUNCH_DISMISS_FILE_ENV = "F8STUDIO_LAUNCH_DISMISS_FILE"
AUTOMATION_ENABLED_ENV = "F8_PYSTUDIO_AUTOMATION"
AUTOMATION_TOKEN_FILE_ENV = "F8_PYSTUDIO_AUTOMATION_TOKEN_FILE"
AUTOMATION_PORT_FILE_ENV = "F8_PYSTUDIO_AUTOMATION_PORT_FILE"
